dist: trusty
sudo: required

language: python

services:
  - docker

addons: # get google-chrome-stable
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
before_install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N https://chromedriver.storage.googleapis.com/77.0.3865.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - docker build -t app .
  - docker run -d --name app -p 8080:5000 -e REACT_APP_ENVIRONMENT=docker -e REACT_APP_TIMEZONE=America/Pacific app
  - docker ps -a
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - /usr/local/bin/chromedriver --version
  - /usr/bin/google-chrome-stable --version
  - python seltest.py