version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t app .
      - run: docker run -d --name app -p 8080:5000 -e REACT_APP_ENVIRONMENT=docker -e REACT_APP_TIMEZONE=America/Pacific app
      - run: docker ps -a
      - run: sudo pip install -r requirements.txt
      - run: export DISPLAY=:99.0
      - run: sleep 15
      - run: python seltest.py
      - run: google-chrome --version